import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Maximize2, Download, X, FileText, FileEdit, Presentation } from "lucide-react";

export interface ArtifactPayload {
  id: string;
  artifact_type: "notes" | "exam" | "slides";
  theme: string;
  title: string;
  html: string;
  model_used?: string | null;
  line_count: number;
  generation_time_ms?: number;
}

function downloadHTML(html: string, filename: string) {
  const clean = html.trim().replace(/^```html\n?/, "").replace(/^```\n?/, "").replace(/```$/, "").trim();
  const blob = new Blob([clean], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url; a.download = filename;
  document.body.appendChild(a); a.click(); document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export const ArtifactCard = ({ artifact }: { artifact: ArtifactPayload }) => {
  const [expanded, setExpanded] = useState(false);
  const isNotes = artifact.artifact_type === "notes";
  const Icon = isNotes ? FileText : FileEdit;
  const filename = `${artifact.title.replace(/[^a-z0-9]+/gi, "-").toLowerCase()}-${artifact.artifact_type}.html`;

  return (
    <>
      <div className="rounded-xl overflow-hidden border border-border/15 bg-muted/8 shadow-sm">
        {/* Header */}
        <div className="flex items-center gap-2 px-3 py-2 border-b border-border/10 bg-background/40">
          <Icon className="w-3.5 h-3.5 text-primary flex-shrink-0" />
          <span className="text-[12px] font-medium truncate flex-1">{artifact.title}</span>
          <span className="text-[9px] px-1.5 py-0.5 rounded-full bg-primary/10 text-primary border border-primary/15 whitespace-nowrap">
            {artifact.theme}
          </span>
          <button
            onClick={() => setExpanded(true)}
            className="p-1 rounded hover:bg-muted/30 text-muted-foreground hover:text-foreground transition"
            title="Expand"
          >
            <Maximize2 className="w-3.5 h-3.5" />
          </button>
          <button
            onClick={() => downloadHTML(artifact.html, filename)}
            className="p-1 rounded hover:bg-muted/30 text-muted-foreground hover:text-foreground transition"
            title="Download"
          >
            <Download className="w-3.5 h-3.5" />
          </button>
        </div>

        {/* Preview iframe (scaled) */}
        <button
          onClick={() => setExpanded(true)}
          className="block w-full text-left cursor-zoom-in"
          style={{ height: 220, overflow: "hidden", position: "relative" }}
        >
          <iframe
            srcDoc={artifact.html}
            sandbox="allow-same-origin"
            title={artifact.title}
            className="border-0 pointer-events-none"
            style={{
              transform: "scale(0.5)",
              transformOrigin: "top left",
              width: "200%",
              height: "440px",
            }}
          />
        </button>

        {/* Footer */}
        <div className="flex items-center justify-between px-3 py-1.5 border-t border-border/10 bg-background/40 text-[10px] text-muted-foreground/70">
          <span>Generated by {artifact.model_used || "Lumina"}</span>
          <span>{artifact.line_count} lines · {artifact.theme}</span>
        </div>
      </div>

      {/* Fullscreen modal */}
      <AnimatePresence>
        {expanded && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-[100] bg-background/95 backdrop-blur-sm flex flex-col"
          >
            <div className="flex items-center px-4 h-12 border-b border-border/15 bg-background">
              <Icon className="w-4 h-4 text-primary mr-2" />
              <span className="text-sm font-medium truncate flex-1">{artifact.title}</span>
              <button
                onClick={() => downloadHTML(artifact.html, filename)}
                className="px-3 py-1.5 rounded-lg bg-primary/15 text-primary hover:bg-primary/25 text-xs font-medium flex items-center gap-1.5 mr-2"
              >
                <Download className="w-3.5 h-3.5" /> Download
              </button>
              <button
                onClick={() => setExpanded(false)}
                className="p-2 rounded-lg hover:bg-muted/30"
              >
                <X className="w-4 h-4" />
              </button>
            </div>
            <iframe
              srcDoc={artifact.html}
              sandbox="allow-same-origin allow-scripts"
              title={artifact.title}
              className="w-full flex-1 border-0 bg-white"
            />
          </motion.div>
        )}
      </AnimatePresence>
    </>
  );
};
