import type { ComputerSkill } from "../computer-skill-library.ts";

export const CATEGORY_2: ComputerSkill[] = [
  { id: "hero-section-craft", category: 2, title: "Hero Section Craft", trigger: ["hero", "landing", "homepage", "first section"],
    conviction: "The hero has about three seconds to make the visitor understand what this is and why to care.",
    do: ["Lead with the specific value proposition", "One clear primary action"], never: "Open with an abstract mission statement." },
  { id: "information-architecture", category: 2, title: "Information Architecture First", trigger: ["navigation", "site map", "pages", "multi-page", "menu"],
    conviction: "Navigation is a promise about where things live.",
    do: ["Map structure before visual design", "Keep nav depth shallow"], never: "Design pages before the sitemap is settled." },
  { id: "responsive-first", category: 2, title: "Responsive-First Layout", trigger: ["responsive", "mobile", "breakpoints", "mobile-first"],
    conviction: "A layout only working at desktop isn't finished.",
    do: ["Design mobile-first", "Verify stacking on narrow viewports"], never: "Ship a fixed-width layout that breaks below 768px." },
  { id: "form-design", category: 2, title: "Form Design Discipline", trigger: ["signup", "contact form", "registration", "checkout", "input"],
    conviction: "Every field is friction — each must justify its presence.",
    do: ["Ask only what's needed", "Clear labels", "Inline validation"], never: "Copy a generic 12-field form." },
  { id: "pricing-table-craft", category: 2, title: "Pricing Table Craft", trigger: ["pricing", "plans", "tiers", "compare plans"],
    conviction: "A pricing table is a decision aid — make the right tier obvious.",
    do: ["Highlight the recommended tier", "Align rows", "Lead with what's included"], never: "Bury the differentiator in checkmarks." },
  { id: "social-proof-placement", category: 2, title: "Testimonial/Social Proof Placement", trigger: ["testimonial", "reviews", "social proof", "logos", "proof"],
    conviction: "Proof works when specific and placed at the moment of doubt.",
    do: ["Place near the CTA or decision point", "Prefer specific claims"], never: "Stack a wall of generic five-star quotes." },
  { id: "accessibility-default", category: 2, title: "Accessibility as Default", trigger: ["accessibility", "screen reader", "alt text", "a11y", "contrast"],
    conviction: "An interface that fails a screen-reader user isn't done.",
    do: ["Semantic HTML", "Alt text", "Focus states", "Logical tab order"], never: "Treat accessibility as optional." },
  { id: "micro-interaction-restraint", category: 2, title: "Micro-Interaction Restraint", trigger: ["animation", "transition", "micro-interaction", "hover"],
    conviction: "Motion should clarify state change, not perform busyness.",
    do: ["Short purposeful transitions", "Keep durations brief"], never: "Add animation for its own sake." },
  { id: "single-vs-multi-page", category: 2, title: "Single vs. Multi-Page Judgment", trigger: ["single page", "one page", "multi page", "multiple pages"],
    conviction: "Structure follows content volume and intent.",
    do: ["Single-page for focused pitch", "Multi-page for distinct audiences"], never: "Force deep content onto endless scroll." },
  { id: "dashboard-data-ui", category: 2, title: "Dashboard/Data UI Craft", trigger: ["dashboard", "monitoring", "analytics ui", "metrics"],
    conviction: "A dashboard answers 'what needs my attention now' at a glance.",
    do: ["Put the most decision-relevant number most prominently", "Group related metrics"], never: "Arrange by what was easiest to generate." },
  { id: "footer-utility", category: 2, title: "Footer as Utility", trigger: ["footer"],
    conviction: "A footer exists to be useful when someone scrolls for something specific.",
    do: ["Real links: contact, key pages", "Proportionate to scope"], never: "Ship an empty or decorative footer." },
  { id: "seo-meta", category: 2, title: "SEO/Meta Fundamentals", trigger: ["seo", "meta description", "title tag", "public site"],
    conviction: "A page that can't be previewed is incomplete.",
    do: ["Real title + meta description", "Semantic heading hierarchy"], never: "Leave default meta tags." },
  { id: "dark-mode-system", category: 2, title: "Dark Mode as a System", trigger: ["dark mode", "dark theme", "night"],
    conviction: "Dark mode is a separate design pass, not an invert filter.",
    do: ["Dedicated colors with correct contrast", "Check data-viz contrast"], never: "Auto-invert light mode." },
  { id: "content-first-layout", category: 2, title: "Content-First Layout", trigger: ["lorem ipsum", "placeholder", "layout"],
    conviction: "Layout serves real content.",
    do: ["Write actual copy before finalizing layout", "Adjust to real length"], never: "Ship lorem ipsum." },
  { id: "loading-empty-states", category: 2, title: "Loading and Empty States", trigger: ["loading", "empty state", "spinner", "async"],
    conviction: "What users see while waiting is part of the interface.",
    do: ["Design explicit loading and empty states"], never: "Leave blank/variable screens." },
  { id: "portfolio-voice", category: 2, title: "Portfolio/Personal Site Voice", trigger: ["portfolio", "personal site", "resume site"],
    conviction: "A portfolio makes the work legible fast.",
    do: ["Lead with problem + outcome per project", "Distinct personal voice"], never: "Template into agency-brochure language." },
];