import type { ComputerSkill } from "../computer-skill-library.ts";

export const CATEGORY_5: ComputerSkill[] = [
  { id: "source-triangulation", category: 5, title: "Source Triangulation", trigger: ["research", "factual", "source", "cross-check", "verify"],
    conviction: "One source is an assertion; independent sources agreeing is a fact.",
    do: ["Cross-check load-bearing claims against multiple sources"], never: "Present a single source as settled." },
  { id: "primary-source", category: 5, title: "Primary-Source Preference", trigger: ["study", "official filing", "original research", "primary"],
    conviction: "A summary of a summary loses accuracy — go closer to the source.",
    do: ["Prefer the original study/filing when it matters"], never: "Cite a blog's paraphrase over the study." },
  { id: "contradiction-handling", category: 5, title: "Contradiction Handling", trigger: ["disagree", "contradicting", "conflicting sources", "contrary"],
    conviction: "Disagreement between credible sources is information.",
    do: ["Surface the disagreement and explain what drives it"], never: "Smooth over or silently choose." },
  { id: "recency-weighting", category: 5, title: "Recency Weighting", trigger: ["recent", "outdated", "current", "changes over time"],
    conviction: "A stale fact stated confidently is worse than an honest caveat.",
    do: ["Prioritize and date recent sources on fast topics"], never: "Present old data as current." },
  { id: "research-depth-calibration", category: 5, title: "Depth Calibration", trigger: ["in-depth", "literature", "research depth"],
    conviction: "Research effort matches the question's stakes.",
    do: ["Scale sources and passes to consequence and contest"], never: "One shallow search on a high-stakes question." },
  { id: "claim-level-sourcing", category: 5, title: "Claim-Level Sourcing", trigger: ["source", "synthesize", "cite"],
    conviction: "Every non-obvious claim should be traceable.",
    do: ["Attribute specific claims to specific sources"], never: "A generic bundled citation list." },
  { id: "gap-identification", category: 5, title: "Gap Identification", trigger: ["literature review", "what is known", "gaps"],
    conviction: "What isn't known is as informative as what is.",
    do: ["Note where evidence is thin or absent"], never: "Present research as comprehensive with real gaps." },
  { id: "quant-qual-balance", category: 5, title: "Quantitative/Qualitative Balance", trigger: ["statistic", "number", "context", "survey"],
    conviction: "A number without context can mislead.",
    do: ["Pair stats with the context to interpret them"], never: "Report a striking stat without context." },
  { id: "low-quality-filtering", category: 5, title: "Low-Quality Source Filtering", trigger: ["source quality", "aggregator", "content farm", "reliable"],
    conviction: "Not all sources deserve equal weight.",
    do: ["Prefer original reporting and peer-reviewed sources"], never: "Cite an aggregator as a primary." },
  { id: "comparative-research", category: 5, title: "Comparative Research Structure", trigger: ["compare", "comparison research", "vs"],
    conviction: "A fair comparison uses the same criteria for every option.",
    do: ["Apply identical criteria and depth to each side"], never: "Research one side deeply and the other flat." },
  { id: "synthesis-over-aggregation", category: 5, title: "Synthesis Over Aggregation", trigger: ["synthesis", "research", "sources"],
    conviction: "The value is the synthesis, not the collection.",
    do: ["Integrate findings into a coherent answer"], never: "Paste source summaries one after another." },
  { id: "uncertainty-disclosure", category: 5, title: "Uncertainty Disclosure", trigger: ["uncertain", "mixed evidence", "research"],
    conviction: "Confident prose over uncertain findings is misreading.",
    do: ["State plainly when evidence is mixed or thin"], never: "Smooth over uncertainty for authority." },
];