import type { ComputerSkill } from "../computer-skill-library.ts";

export const CATEGORY_7: ComputerSkill[] = [
  { id: "exam-prep", category: 7, title: "Exam-Prep Material Design", trigger: ["revision", "exam prep", "cheat sheet", "past paper"],
    conviction: "Exam-prep material mirrors how the exam will test the material.",
    do: ["Weight toward what's likely tested", "Organize by exam structure"], never: "A generic syllabus summary with no relation to assessment." },
  { id: "flashcard-design", category: 7, title: "Flashcard Design", trigger: ["flashcard", "cards", "recall"],
    conviction: "A good flashcard tests recall of one atomic fact.",
    do: ["One question, one answer per card", "Phrase to avoid pattern-matching"], never: "Cram multiple facts onto a card." },
  { id: "spaced-repetition", category: 7, title: "Spaced-Repetition-Aware Sequencing", trigger: ["spaced repetition", "review schedule", "forgetting curve"],
    conviction: "Review timing follows forgetting curves.",
    do: ["Space revisits increasingly apart", "prioritize weak areas"], never: "Uniform review regardless of mastery." },
  { id: "transcription-cleanup", category: 7, title: "Lecture Transcription Cleanup", trigger: ["transcript", "lecture notes", "transcription"],
    conviction: "A transcript is data; notes are a usable artifact.",
    do: ["Remove filler", "restructure with headings", "keep real content"], never: "Hand back a lightly formatted transcript." },
  { id: "concept-map", category: 7, title: "Concept Map Generation", trigger: ["concept map", "relationship diagram", "mind map"],
    conviction: "A concept map shows actual relationships.",
    do: ["Draw labeled relationships", "keep readable depth"], never: "A word cloud with generic lines." },
  { id: "practice-question-blum", category: 7, title: "Practice Question Design", trigger: ["practice questions", "bloom", "application question", "quiz"],
    conviction: "Real understanding is tested at multiple cognitive levels.",
    do: ["Mix recall, application, analysis"], never: "Recall-only recall sets." },
  { id: "study-schedule", category: 7, title: "Study Schedule Generation", trigger: ["study schedule", "timetable", "study plan"],
    conviction: "A schedule only works if it's realistic to follow.",
    do: ["Account for available time", "prioritize weak/high-weightage", "build in review"], never: "An idealized schedule." },
  { id: "revision-summary", category: 7, title: "Summarization for Revision", trigger: ["revision summary", "condense", "exam notes"],
    conviction: "A revision summary is usable the night before.",
    do: ["Prioritize testable facts", "scannable format"], never: "A slightly shorter version of the original prose." },
  { id: "mnemonic-construction", category: 7, title: "Mnemonic Construction", trigger: ["mnemonic", "memorize", "remember list"],
    conviction: "A good mnemonic is memorable because it's a little absurd.",
    do: ["Vivid specific associations"], never: "Bland acronyms with no imagery." },
  { id: "past-paper-analysis", category: 7, title: "Past-Paper Pattern Analysis", trigger: ["past paper", "exam pattern", "weightage"],
    conviction: "Past papers reveal the exam's actual habits.",
    do: ["Identify recurring patterns across multiple papers"], never: "Generalize from a single paper." },
  { id: "difficulty-calibration", category: 7, title: "Difficulty Calibration", trigger: ["difficulty", "student level", "struggling"],
    conviction: "Same content needs different entry points by level.",
    do: ["Use level to set depth", "scaffold up"], never: "Default difficulty for everyone." },
  { id: "board-alignment", category: 7, title: "Syllabus and Board Alignment", trigger: ["cbse", "icse", "board", "curriculum", "syllabus"],
    conviction: "A student's board defines what's correct and relevant.",
    do: ["Align terminology/methods/scope to the board"], never: "Silently use the wrong convention." },
  { id: "gamification", category: 7, title: "Gamification Element Design", trigger: ["gamification", "points", "badges", "rewards", "streak"],
    conviction: "Gamification rewards the actual learning behavior.",
    do: ["Tie rewards to real signals"], never: "Reward raw time-on-app." },
  { id: "progress-honesty", category: 7, title: "Progress Tracking Honesty", trigger: ["progress", "mastery indicator", "progress report"],
    conviction: "A progress indicator the student trusts is valuable.",
    do: ["Base on genuine data", "show weak areas plainly"], never: "Inflate a metric." },
  { id: "peer-teaching", category: 7, title: "Peer-Teaching Material Design", trigger: ["explain to someone", "teach a friend", "peer"],
    conviction: "Explaining tests real understanding.",
    do: ["Structure around questions the student answers in their own words"], never: "Just the original explanation." },
];