import type { ComputerSkill } from "../computer-skill-library.ts";

export const CATEGORY_3: ComputerSkill[] = [
  { id: "doc-structure-first", category: 3, title: "Document Structure Before Prose", trigger: ["document", "multi-section", "report", "white paper"],
    conviction: "A reader should navigate from headings alone before reading body text.",
    do: ["Draft the heading skeleton first", "Write prose into it"], never: "Write linearly and retrofit headings." },
  { id: "exec-summary-discipline", category: 3, title: "Executive Summary Discipline", trigger: ["executive summary", "report", "brief", "summary"],
    conviction: "The summary is the document for a reader who reads nothing else.",
    do: ["Conclusion + key support + recommended action"], never: "Restate the table of contents." },
  { id: "citation-hygiene", category: 3, title: "Citation Hygiene", trigger: ["cite", "source", "reference", "claims", "factual"],
    conviction: "An unverifiable claim is a liability.",
    do: ["Attribute to actual source", "Flag uncertain claims"], never: "Invent a citation or statistic." },
  { id: "table-readability", category: 3, title: "Table Design for Readability", trigger: ["table", "tabular", "data table", "columns"],
    conviction: "A table's job is comparison.",
    do: ["Order by relevance", "Align units", "Highlight the key row/column"], never: "Dump raw data with no ordering." },
  { id: "formal-correspondence", category: 3, title: "Formal Correspondence Register", trigger: ["letter", "formal email", "official", "correspondence"],
    conviction: "Formal register is precision, not stiffness.",
    do: ["Match tone to relationship", "State purpose in first two sentences"], never: "Bloat with boilerplate." },
  { id: "resume-craft", category: 3, title: "Resume/CV Craft", trigger: ["resume", "cv", "curriculum vitae"],
    conviction: "Every resume line proves a specific capability with a result.",
    do: ["Lead with outcomes and numbers", "Cut duty-description-only", "language"], never: "Generic responsibility statements." },
  { id: "cover-letter-specificity", category: 3, title: "Cover Letter Specificity", trigger: ["cover letter"],
    conviction: "A cover letter is clearly about this role at this company.",
    do: ["Reference something real and specific", "Connect to the candidate"], never: "A swappable generic template." },
  { id: "proposal-structure", category: 3, title: "Proposal Structure", trigger: ["proposal", "business proposal"],
    conviction: "A proposal must answer 'why this, why now, why us'.",
    do: ["Problem, solution, proof, terms", "Lead with the problem"], never: "Open with company history." },
  { id: "technical-docs-clarity", category: 3, title: "Technical Documentation Clarity", trigger: ["how to", "docs", "api", "guide", "tutorial", "setup"],
    conviction: "Docs are tested by whether a stranger can follow them.",
    do: ["Imperative ordered steps", "Prerequisites up front", "Success signals per step"], never: "Narrative when a procedure is needed." },
  { id: "meeting-notes", category: 3, title: "Meeting Notes Structure", trigger: ["meeting notes", "minutes", "action items"],
    conviction: "Notes exist for people who weren't there and those who committed.",
    do: ["Separate decisions, actions (with owners), context"], never: "Undifferentiated transcript." },
  { id: "whitepaper-depth", category: 3, title: "Whitepaper Depth Calibration", trigger: ["whitepaper", "in-depth", "explainer"],
    conviction: "Depth tracks genuine complexity, not page count.",
    do: ["Go deep as the argument needs", "Stop when the case is made"], never: "Pad to hit a length." },
  { id: "contract-precision", category: 3, title: "Contract-Adjacent Precision", trigger: ["terms", "agreement", "contract", "legal"],
    conviction: "Ambiguous language here is a real risk.",
    do: ["Precise unambiguous terms", "Flag non-substitute for legal review"], never: "Smooth over ambiguity." },
  { id: "long-doc-navigation", category: 3, title: "Long-Document Navigation Aids", trigger: ["long document", "table of contents", "thesis"],
    conviction: "A long doc without navigation punishes the reader.",
    do: ["TOC", "consistent headings", "page/section references"], never: "Ship a 20-page doc with no way to jump." },
  { id: "revision-aware-editing", category: 3, title: "Revision-Aware Editing", trigger: ["edit", "revision", "rewrite"],
    conviction: "A good edit preserves the author's voice.",
    do: ["Preserve structure and voice", "Change only what needs changing"], never: "Rewrite the whole document." },
  { id: "plain-language", category: 3, title: "Plain-Language Default", trigger: ["plain", "simple language", "jargon"],
    conviction: "Complexity comes from the subject, not the writer.",
    do: ["Simplest phrasing that's accurate", "Define jargon on first use"], never: "Reach for a longer word." },
  { id: "doc-length-calibration", category: 3, title: "Document Length Calibration", trigger: ["length", "brief", "comprehensive"],
    conviction: "Length is a function of what content needs.",
    do: ["Stop when the point is made"], never: "Pad to seem substantial." },
];