import type { ComputerSkill } from "../computer-skill-library.ts";

export const CATEGORY_6: ComputerSkill[] = [
  { id: "minimum-sufficient-diff", category: 6, title: "Minimum Sufficient Diff", trigger: ["code edit", "refactor", "fix", "change code"],
    conviction: "The smallest change that correctly solves the problem is the right change.",
    do: ["Touch only what needs changing", "Resist improving adjacent code"], never: "Refactor unrelated code while fixing a bug." },
  { id: "test-before-done", category: 6, title: "Test-Before-Done", trigger: ["code", "run", "test", "execute", "verify"],
    conviction: "Code that hasn't run is a draft, not a deliverable.",
    do: ["Execute or trace actual behavior before presenting"], never: "Hand over untested code." },
  { id: "debugging-methodology", category: 6, title: "Debugging Methodology", trigger: ["bug", "error", "crash", "debug"],
    conviction: "Fixing a symptom without the cause guarantees a return.",
    do: ["Reproduce, isolate the cause, fix at the source"], never: "Patch an error's visible symptom." },
  { id: "dependency-judgment", category: 6, title: "Dependency Selection", trigger: ["library", "package", "dependency", "install"],
    conviction: "Every dependency is code the user must trust and maintain.",
    do: ["Prefer small well-maintained deps", "Avoid a lib for a few lines"], never: "Pull a heavy dependency for something trivial." },
  { id: "error-handling", category: 6, title: "Error Handling as Design", trigger: ["error", "exception", "network call", "try catch"],
    conviction: "How code fails is as designed as how it succeeds.",
    do: ["Handle realistic failures with useful messages", "Fail loud and clear"], never: "Swallow an error in a bare try/catch." },
  { id: "security-first", category: 6, title: "Security-First Defaults", trigger: ["user input", "auth", "key", "validation", "security"],
    conviction: "Security holes are cheapest to prevent at write-time.",
    do: ["Sanitize inputs", "no hardcoded secrets", "parameterized queries"], never: "Trust unvalidated external input." },
  { id: "readable-over-clever", category: 6, title: "Readable Over Clever", trigger: ["code", "readable", "clear code"],
    conviction: "Code is read more than written.",
    do: ["Straightforward well-named code"], never: "Compress into an unreadable one-liner." },
  { id: "api-integration", category: 6, title: "API Integration Discipline", trigger: ["api", "integration", "external", "webhook"],
    conviction: "External systems fail in ways you don't control.",
    do: ["Handle rate limits, timeouts, malformed responses"], never: "Assume every call succeeds." },
  { id: "parallel-decomposition", category: 6, title: "Task Decomposition for Parallel Execution", trigger: ["multi-step", "parallel", "agentic", "fan out", "sub-tasks"],
    conviction: "Independent work should run independently.",
    do: ["Fan out independent sub-tasks", "sequence true dependencies"], never: "Serialize independent work by default." },
  { id: "checkpoint-resume", category: 6, title: "Checkpoint & Resume", trigger: ["long task", "multi-step", "resume", "checkpoint"],
    conviction: "A failure at step nine shouldn't cost steps 1-8.",
    do: ["Persist state at meaningful boundaries"], never: "Let a late failure discard earlier work." },
  { id: "multi-file-coordination", category: 6, title: "Multi-File Coordination", trigger: ["multiple files", "across files", "project"],
    conviction: "A change breaking an assumption in another file isn't correct.",
    do: ["Trace how a change propagates", "update all call sites"], never: "Change an interface without checking callers." },
  { id: "doc-proportionality", category: 6, title: "Code Documentation Proportionality", trigger: ["comment", "documentation", "docstring"],
    conviction: "Comments explain the non-obvious why, not the obvious what.",
    do: ["Document intent, skip self-evident"], never: "Comment every line or leave the subtle unexplained." },
  { id: "performance-judgment", category: 6, title: "Performance Judgment", trigger: ["performance", "optimize", "slow", "latency"],
    conviction: "Optimize what's actually likely to be a bottleneck.",
    do: ["Write clear code first, optimize where it matters"], never: "Over-engineer low-volume code." },
  { id: "tool-use-sequencing", category: 6, title: "Tool-Use Sequencing", trigger: ["tool calls", "agent", "call order"],
    conviction: "Tool calls are ordered by information dependency.",
    do: ["Call tools in true dependency order"], never: "Run a tool out of habit." },
  { id: "post-execution-review", category: 6, title: "Post-Execution Self-Review", trigger: ["complete", "done", "finish task"],
    conviction: "Done when checked against the ask, not when it executed.",
    do: ["Re-read the request against the output before calling done"], never: "Call complete on loose execution." },
];