import type { ComputerSkill } from "../computer-skill-library.ts";

export const CATEGORY_4: ComputerSkill[] = [
  { id: "formula-transparency", category: 4, title: "Formula Transparency", trigger: ["formula", "spreadsheet", "calculated", "cell"],
    conviction: "A formula the user can't audit is one they can't trust.",
    do: ["Clear traceable formulas", "Name ranges/cells meaningfully"], never: "Hardcode a value that should be a formula." },
  { id: "data-cleaning", category: 4, title: "Data Cleaning Before Analysis", trigger: ["raw data", "messy", "clean data", "dataset"],
    conviction: "Analysis on unclean data is confidently wrong.",
    do: ["Check duplicates, formats, missing values before building"], never: "Build on unchecked data." },
  { id: "summary-table-design", category: 4, title: "Summary Table Design", trigger: ["pivot", "summary table", "aggregate"],
    conviction: "A summary table answers a specific question.",
    do: ["Design around the actual decision", "Keep relevant dimensions"], never: "Build a maximal pivot." },
  { id: "spreadsheet-chart-selection", category: 4, title: "Chart Selection for Data", trigger: ["sheet chart", "spreadsheet chart", "pivot chart"],
    conviction: "Chart type is a claim about the data's shape.",
    do: ["Match type to relationship", "Avoid distorting 3D/decorative"], never: "Default to whatever is suggested first." },
  { id: "conditional-formatting", category: 4, title: "Conditional Formatting for Signal", trigger: ["conditional formatting", "highlight", "format rules"],
    conviction: "Formatting should draw the eye to what matters.",
    do: ["Apply narrowly to actionable thresholds"], never: "Rainbow-format the whole sheet." },
  { id: "financial-model-structure", category: 4, title: "Financial Model Structure", trigger: ["budget", "forecast", "financial model", "assumptions"],
    conviction: "A model makes its assumptions visible and editable.",
    do: ["Separate an assumptions section from output", "Label every assumption"], never: "Bury assumptions in formulas." },
  { id: "dashboard-sheet-craft", category: 4, title: "Dashboard Sheet Craft", trigger: ["dashboard sheet", "at-a-glance", "summary tab"],
    conviction: "A dashboard tab is read in seconds.",
    do: ["Surface only the numbers that matter", "Push detail to other tabs"], never: "Turn the dashboard into another data tab." },
  { id: "data-validation", category: 4, title: "Data Validation Guardrails", trigger: ["data validation", "editable sheet", "dropdown", "user input sheet"],
    conviction: "A sheet that accepts bad input will get bad input.",
    do: ["Add validation/dropdowns/limits where errors are likely"], never: "Leave an editable field unvalidated." },
  { id: "budget-tracker-usability", category: 4, title: "Budget/Tracker Sheet Usability", trigger: ["budget tracker", "expense tracker", "personal tracker"],
    conviction: "A tracker only works if updating it is easy.",
    do: ["Minimize fields per entry", "Automate totals/categorization"], never: "Design a tracker that's painful to update." },
  { id: "grade-progress-tracking", category: 4, title: "Grade/Progress Tracking Design", trigger: ["grade tracker", "progress sheet", "marks"],
    conviction: "A student tracking progress needs trend visibility.",
    do: ["Show trajectory over time", "Flag below-target areas"], never: "A static score table with no trend." },
  { id: "cross-sheet-consistency", category: 4, title: "Cross-Sheet Consistency", trigger: ["multiple sheets", "workbook", "tabs"],
    conviction: "A workbook behaves like one coherent tool.",
    do: ["Consistent naming, units, formats", "Link related tabs"], never: "Compute the same metric differently." },
  { id: "explain-the-number", category: 4, title: "Explain-the-Number Annotation", trigger: ["note", "methodology", "non-obvious number"],
    conviction: "A number without context can't be verified.",
    do: ["Add cell notes or methodology for non-trivial calcs"], never: "Leave a key output number unexplained." },
];