import type { ComputerSkill } from "../computer-skill-library.ts";

export const CATEGORY_1: ComputerSkill[] = [
  { id: "deck-narrative-arc", category: 1, title: "Deck Narrative Arc", trigger: ["deck", "slides", "presentation", "storyboard", "multi-slide", "argument"],
    conviction: "A deck is an argument with a beginning, middle, and end — not a stack of facts.",
    do: ["Identify the one thing the audience should believe by the last slide, then build every slide to earn it", "Cut anything that doesn't serve the arc"], never: "Open the design before knowing what the deck is trying to convince someone of." },
  { id: "title-slide-craft", category: 1, title: "Title Slide Craft", trigger: ["title", "opening", "cover slide", "first slide"],
    conviction: "A title slide is a promise, not a label.",
    do: ["State the specific claim or outcome, not the generic topic", "One strong line plus a subline of context", "Skip decorative filler"], never: "Ship 'Company Overview' when a real claim is available." },
  { id: "data-density-judgment", category: 1, title: "Data-Density Judgment", trigger: ["chart", "statistic", "graph", "table", "dashboard"],
    conviction: "A slide holds one idea; a report holds many.",
    do: ["One chart, one takeaway per slide", "Move supporting detail to notes or appendix", "Label the 'so what' on the slide"], never: "Paste a dense table and call it the data slide." },
  { id: "chart-type-selection", category: 1, title: "Chart-Type Selection", trigger: ["chart", "graph", "visualize", "plot", "trend"],
    conviction: "The chart type is a claim about the relationship in the data.",
    do: ["Trend -> line", "Comparison -> bar", "Part-of-whole -> stacked bar or pie if <=4 segments", "Correlation -> scatter"], never: "Pick a chart for looks rather than correctness." },
  { id: "comparison-slide-structure", category: 1, title: "Comparison Slide Structure", trigger: ["vs", "versus", "comparison", "before", "after", "options"],
    conviction: "A comparison slide lets the eye find the difference in under two seconds.",
    do: ["Align comparable rows exactly", "Consistent units and scale", "Highlight the point of difference visually"], never: "List two unaligned bullet columns and call it a comparison." },
  { id: "timeline-process-slide", category: 1, title: "Timeline / Process Slide", trigger: ["timeline", "roadmap", "process", "sequence", "stages", "history"],
    conviction: "Time and sequence are spatial — they should look spatial.",
    do: ["Lay stages left-to-right/top-to-bottom with connectors", "Mark the 'you are here' point", "Terse stage labels"], never: "Represent a sequence as an unordered bullet list." },
  { id: "text-density-enforcement", category: 1, title: "Text Density Enforcement", trigger: ["too much text", "bullet", "dense", "paragraph on slide"],
    conviction: "A slide is a prompt for speech, not a document to be read.",
    do: ["Cap body text hard", "Push full sentences into notes", "Fragments and strong nouns on-slide"], never: "Let a slide become a paragraph with bullets sprinkled in." },
  { id: "deck-visual-system", category: 1, title: "Deck-Level Visual System", trigger: ["consistent", "theme", "font", "palette", "grid", "visual system"],
    conviction: "Consistency is what makes a deck look designed.",
    do: ["Fix type, color, grid before the first content slide", "Reuse them exactly everywhere"], never: "Let each slide invent its own sizes or colors." },
  { id: "code-based-visual-generation", category: 1, title: "Code-Based Visual Generation", trigger: ["svg", "diagram", "icon", "generate chart", "no image"],
    conviction: "A well-built SVG or programmatic chart beats a mediocre stock image.",
    do: ["Generate charts/diagrams as inline SVG or via pptxgenjs", "Default to this path"], never: "Leave a placeholder box captioned '[image here]'." },
  { id: "executive-summary-slide", category: 1, title: "Executive Summary Slide", trigger: ["executive", "summary slide", "report deck"],
    conviction: "Someone who reads only slide 2 should still get the point.",
    do: ["Conclusion + key evidence + next step in three lines max"], never: "Make the summary a preview of what's coming." },
  { id: "closing-cta-slide", category: 1, title: "Closing / CTA Slide", trigger: ["last slide", "closing", "thank you"],
    conviction: "A deck that trails off wastes everything before it.",
    do: ["End on a specific, actionable line, not 'Thank You'"], never: "Let the final slide be decorative." },
  { id: "speaker-notes-discipline", category: 1, title: "Speaker Notes Discipline", trigger: ["speaker notes", "presented live"],
    conviction: "Notes carry what the slide can't hold, not a transcript.",
    do: ["Write talking points including transitions"], never: "Duplicate the on-slide text into the notes." },
  { id: "quote-callout-slide", category: 1, title: "Quote / Callout Slide", trigger: ["testimonial", "quote", "callout", "pull quote"],
    conviction: "A quote slide earns its place by being genuinely quotable.",
    do: ["Single strongest sentence", "Attribute clearly", "Visual weight, not clutter"], never: "Run a full paragraph as a quote." },
  { id: "appendix-backup-slides", category: 1, title: "Appendix / Backup Slides", trigger: ["appendix", "backup", "supporting detail"],
    conviction: "Depth belongs in reserve, not in the main narrative's way.",
    do: ["Move detailed data and edge cases to a marked appendix"], never: "Bloat the core deck." },
  { id: "template-breaking-judgment", category: 1, title: "Template-Breaking Judgment", trigger: ["template", "rigid", "layout"],
    conviction: "A template is a scaffold, not a cage.",
    do: ["Deviate from default layout when content calls for it"], never: "Force content into a layout that doesn't fit." },
  { id: "pacing-across-deck", category: 1, title: "Pacing Across a Deck", trigger: ["long deck", "rhythm", "pacing"],
    conviction: "A deck has rhythm — dense slides need a lighter one to breathe.",
    do: ["Alternate deep slides with simple transition slides"], never: "Run ten dense slides in a row." },
  { id: "brand-consistency", category: 1, title: "Brand Consistency", trigger: ["brand", "logo colors", "brand fonts"],
    conviction: "Brand constraints make a deck look legitimate.",
    do: ["Apply stated colors/fonts exactly and consistently"], never: "Drift from the brand across slides." },
  { id: "section-divider-slides", category: 1, title: "Section Divider Slides", trigger: ["sections", "divider", "section break"],
    conviction: "A section break resets attention.",
    do: ["Use a visually distinct, low-text divider"], never: "Jump topics with no visual signal." },
];