// Export Lumina Computer sheet blocks to a real .xlsx workbook with live formulas.
import ExcelJS from "exceljs";
import type { LcBlock } from "./api";

type SheetJson = {
  tab_name?: string;
  columns?: string[];
  rows?: any[][];
  formulas?: Record<string, string>; // e.g. { "C2": "=B2*1.1" }
};

// Per XLSX skill: professional font (Calibri), financial-model colors
const ACCENT = "FF2DD4BF";
const HEADER_BG = "FF111827";
const HEADER_TX = "FFF8FAFC";
const ZEBRA = "FFF1F5F9";
const FONT = "Calibri";
const INPUT_COLOR = "FF0000FF"; // blue for hardcoded inputs
const FORMULA_COLOR = "FF000000"; // black for formulas

function colLetter(i: number) {
  let n = i + 1;
  let s = "";
  while (n > 0) {
    const r = (n - 1) % 26;
    s = String.fromCharCode(65 + r) + s;
    n = Math.floor((n - 1) / 26);
  }
  return s;
}

export async function exportSheetsToXlsx(projectTitle: string, blocks: LcBlock[]) {
  const wb = new ExcelJS.Workbook();
  wb.creator = "Lumina Computer";
  wb.created = new Date();

  const sheetBlocks = blocks.filter((b) => b.block_type === "sheet_tab" && b.content_json);
  if (sheetBlocks.length === 0) {
    // Fallback stub so file isn't empty
    wb.addWorksheet("Empty");
  }

  const usedNames = new Set<string>();

  for (const [idx, block] of sheetBlocks.entries()) {
    const data = (block.content_json ?? {}) as SheetJson;
    let name = (data.tab_name || block.title || `Sheet${idx + 1}`)
      .replace(/[\\/*?:[\]]/g, " ").slice(0, 31).trim() || `Sheet${idx + 1}`;
    // dedupe
    let base = name, k = 2;
    while (usedNames.has(name.toLowerCase())) { name = `${base} (${k++})`.slice(0, 31); }
    usedNames.add(name.toLowerCase());

    const ws = wb.addWorksheet(name, {
      views: [{ state: "frozen", ySplit: 1 }],
      properties: { defaultColWidth: 18 },
    });

    const cols = (data.columns ?? []).map((c) => String(c ?? ""));
    const rows = (data.rows ?? []).map((r) => (Array.isArray(r) ? r : [r]));

    // Header row
    if (cols.length) {
      const header = ws.addRow(cols);
      header.font = { bold: true, color: { argb: HEADER_TX }, name: FONT, size: 11 };
      header.alignment = { vertical: "middle", horizontal: "left" };
      header.height = 22;
      header.eachCell((cell) => {
        cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: HEADER_BG } };
        cell.border = { bottom: { style: "medium", color: { argb: ACCENT } } };
      });
    }

    // Data rows
    for (const [ri, row] of rows.entries()) {
      const r = ws.addRow(row);
      r.font = { name: FONT, size: 11 };
      r.alignment = { vertical: "middle" };
      if (ri % 2 === 1) {
        r.eachCell((cell) => {
          cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: ZEBRA } };
        });
      }
      // Auto-number formatting
      r.eachCell((cell) => {
        if (typeof cell.value === "number") {
          cell.numFmt = Number.isInteger(cell.value) ? "#,##0" : "#,##0.00";
          cell.alignment = { ...cell.alignment, horizontal: "right" };
        }
      });
    }

    // Formulas overlay — cell refs are 1-indexed in ExcelJS.
    // Model has header at row 1, so JSON refs "C2" line up directly.
    const formulas = data.formulas ?? {};
    for (const [ref, formula] of Object.entries(formulas)) {
      try {
        const f = String(formula ?? "").trim();
        if (!f) continue;
        const cell = ws.getCell(ref);
        cell.value = { formula: f.startsWith("=") ? f.slice(1) : f } as any;
        cell.font = { name: FONT, size: 11, color: { argb: FORMULA_COLOR } };
      } catch { /* ignore bad refs */ }
    }

    // Auto-size columns (rough)
    ws.columns.forEach((col, i) => {
      let max = cols[i] ? cols[i].length : 8;
      for (const row of rows) {
        const v = row[i];
        if (v == null) continue;
        const len = String(v).length;
        if (len > max) max = len;
      }
      col.width = Math.min(Math.max(max + 3, 10), 42);
    });

    // Footer note with model attribution
    if (block.model_used) {
      const noteRow = ws.addRow([]);
      const nr = ws.addRow([`Generated by ${block.model_used} · Lumina Computer`]);
      nr.font = { italic: true, color: { argb: "FF64748B" }, size: 9, name: FONT };
      ws.mergeCells(nr.number, 1, nr.number, Math.max(cols.length, 1));
      void noteRow;
    }
  }

  const buf = await wb.xlsx.writeBuffer();
  const safe = projectTitle.replace(/[^\w\-. ]+/g, "").slice(0, 60) || "sheets";
  const blob = new Blob([buf], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${safe}.xlsx`;
  a.click();
  URL.revokeObjectURL(url);
}
