-- :free suffix is required by OpenRouter free-tier models, so we keep it in the DB.
-- The normalizeModelId function in lc-llm-router was updated to NOT strip :free.
-- This migration is intentionally a no-op.